### ISSUE TITLE
/opt/scripts/iobroker_startup.sh: Zeile 197: [: !=: Einstelliger (unärer) Operator erwartet.

### ISSUE THREAD

**Issue by JoergKimmich** [buanet/docker-iobroker#151]
get Error Message  "/opt/scripts/iobroker_startup.sh: Zeile 197: [: !=: Einstelliger (unärer) Operator erwartet." don't know what's going wrong. First time building the Container it runs without Error. On every build after the first build this Error occurs

**Comment by buanet** [comment]
Before I ask you questions about your setup and where the log is, please check this as written in readme.md:

"Important: If the folder you mount to /opt/iobroker in your container is placed on a mounted device, partition or other storage, the mountpoint on your host should NOT have the "noexec" flag activated. Otherwise you may get problems executing ioBroker inside the container!"

Regards,
André

**Comment by JoergKimmich** [comment]
noexec problem, thank you
