### ISSUE TITLE
Enable CIFS / NFS Mounts

### ISSUE THREAD

**Issue by Springjunky** [buanet/docker-iobroker#63]
The iobroker module backitup https://github.com/simatec/ioBroker.backitup/blob/master/docs/de/backitup.md needs some extra packages

```
       nfs-common \
        cifs-utils \
```
to enable backups on dynamical mounted volumes.

Please add this packages .. I've tested the localy and it works with --privileged flag.

Thx

**Comment by duffbeer2000** [comment]
You are able to install the packages witch the "PACKAGES" environment variable. They should not be added to the image itself. And by the way, don't use the privileged flag, it's a big security risk.

**Comment by buanet** [comment]
As backitup is not part of a default iobroker installation I see no reason to add the packages to the Docker image.
For additional packages needed from adapters please use ENV "PACKAGES" as described in readme.md.

BTW, what do you mean with "I've tested the localy and it works with --privileged flag"? 

Regards,
André

**Comment by Springjunky** [comment]
Uh oh, sorry, yes "RTFM" thanks for that hint !

"locally" means I have build a new docker-image on my local pc with this packages and used this to test it with a mount from my QNAP 

Several tries with the capability  SYS_ADMIN gave me a "read-only" mount of the NFS-Mount, only --privileged works correct.
I would gladly prevent --privileged if someone could tell me the correct capabilities  to do a NFS-Mount out of the container.

The NFS volume is set up with "any IP allowed / NO_ROOT_SQUASH"

**Comment by duffbeer2000** [comment]
Ah, now I see the problem with the mount inside the container. I think it would be better to mount the nfs share outside the container to prevent the privileged option. Because I don't use a NFS-Mount I'm not sure if that works but I found two Howto manuals. I will setup a NFS-Share on my NAS and test it this week:
[Mounting a NFS Directory into Host Volume](https://unix.stackexchange.com/questions/292999/mounting-a-nfs-directory-into-host-volume-that-is-shared-with-docker)
[Docker (Swarm) and NFS volumes](https://blog.dahanne.net/2017/11/20/docker-swarm-and-nfs-volumes/)

**Comment by Springjunky** [comment]
Yes, I know how to mount a volume inside the container.
The iobroke-Module "backitup" ist the problem, a backup-prozess inside the container does the following steps

- mount NFS Volume
- create a tar on this Volume
- unmount the Volume
